### ISSUE TITLE
alarm panel no longer works in hass after updating this and Hass

### ISSUE THREAD

**Issue by CTLS** [JasonCarter80/concord232#8]
Not sure what happened but I can no longer arm/ disarm in home assistant after updating.  All binary sensors still seem to work.

**Comment by rwa** [comment]
Works for me.  Did you maybe need to restart the server to pick up the new version?  Is your server running on the same machine as hass?

**Comment by rwa** [comment]
Oh wait, I've updated to 0.61.0 and am seeing an issue now too.  I'll look into it.

**Comment by rwa** [comment]
Arming works for me.  I am seeing intermittent issues with warnings about max tries exceeded polling the server, but it doesn't seem to cause any serious problems.

Is your server updated to 0.15 and restarted?

Can you arm using this package's client?

concord232_client --host 192.168.1.blah:5007 arm-stay

**Comment by CTLS** [comment]
Yes I just reinstalled the server.  I can disarm and I can see the sensors in home assistant.  I am wondering if maybe the client didn't update for home assistant?  I am not sure how to force that to update though.

**Comment by CTLS** [comment]
I attempted to arm using the client and that does not work either.
My alarm is directly connected to the home assistant raspberry pi.
I will say I could arm the alarm from the client before I uninstalled and reinstalled the concord232 server.

**Comment by rwa** [comment]
One thing that needs to be done is to make the client and server both report their version numbers.  That would help in situations like this.

Any errors in the logs? Either the concord232 server log, or the home assistant log?

**Comment by rwa** [comment]
One thing to note is that the syntax for arming has changed a little.  There is no more "exit" or "auto".  The terminology used on the Concord panels and docs is "away", so "arm-away" is what is used in the client now.  "arm-stay" remains the same.

(and, when you get things working, arm-stay-silent, and arm-stay-instant should work now, too)

**Comment by CTLS** [comment]
Arm-away and arm-stay do not work in the client.  Is there no way to tell which version of the client/ server I have?
Also I have mine auto starting somehow from a long time ago.  Where would the logs for concord232 server be stored so I can check for errors?

**Comment by rwa** [comment]
The client and server don't seem to be set up to report their versions, unfortunately.  I'll fix that soon.  In a pinch we could look at specific lines of code to see if they are the new version or not.  The server takes an optional --log argument that would specify the logfile.  Look in your autostart setup to see what you used for that (or if).

Maybe try installing fresh manually, and then invoking the server from the command line, so you're sure which version you're running, and you can watch the server log which will be written to the terminal:

```
pip3 install --upgrade concord232
```
This should install v0.15.  You may need to sudo the installation.
```
pip3 show -f concord232
```
should show the installed files.  If there is a server already running, kill it.  Something like:

```
ps -ef | grep concord
kill <pid>
```
You may need to use sudo kill or and or kill -9 to make the server stop.  Once it's no longer running, start the new server using the path shown above with something like:
```
/usr/local/bin/concord232_server --serial /dev/ttyUSB0 
```
then open up another terminal, and make sure you're using the client installed above:
```
/usr/local/bin/concord232_client arm-stay
```

If that works, then there's something going on with the older versions getting picked up probably.  If that doesn't work, well then the new version really isn't working for you, and we'll have to diagnose it from there.

**Comment by CTLS** [comment]
I did what you mentioned and it still does not work.  I have copied the logging.  I can disarm, but the arming does not work.
```
2018-01-17 18:22:30,763 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:30] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:32,671 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:32] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:32,711 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:32] "GET /command?cmd=arm&level=stay HTTP/1.1" 200 -
2018-01-17 18:22:34,687 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:34] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:36,710 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:36] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:38,689 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:38] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:40,696 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:40] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:42,686 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:42] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:44,700 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:44] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:46,686 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:46] "GET /zones HTTP/1.1" 200 -
2018-01-17 18:22:48,684 _internal INFO 127.0.0.1 - - [17/Jan/2018 18:22:48] "GET /zones HTTP/1.1" 200 -
```

**Comment by rwa** [comment]
Ok, thanks.  I have some things to suggest once I'm back at my home computer.  I changed the key sequences used for arming from "keyfob" based arming to the "2" or "3" keys that work from the usual alarm keypads.  This works and is more intuitive for me, but maybe it doesn't work for your panel.  We can try sending those sequences as raw bytes to the panel to see which ones work on your panel.

Which alarm panel model do you have?

**Comment by CTLS** [comment]
I have a concord 4,  I am not sure if there are more specific models than that?

**Comment by rwa** [comment]
Same as mine.  We'll get this sorted out.  Thanks for your patience.

**Comment by CTLS** [comment]
fixed it! keyfob arming was disabled in the installer settings on the panel!  might want to mention that in the readme file.

**Comment by rwa** [comment]
Cool!  But that is really weird, since the keyfob arming is what was used originally when I started working on this, and I changed it to use the keypad numbers for this update:

https://github.com/JasonCarter80/concord232/commit/bc7e7a9a65ca13cbec9798ecd14c4d87244775b6

So I'm a little confused about what to write in the README.

**Comment by CTLS** [comment]
That is strange.  I didn't change anything on the panel settings before today.

**Comment by rwa** [comment]
Since I'm not sure how to explain this, I think I'll wait for a repeat of this issue to make a note of it in the README.
